# Write your MySQL query statement below
-- SELECT P.PRODUCT_NAME ,SUM(O.UNIT) FROM PRODUCTS P
-- JOIN ORDERS O ON P.PRODUCT_ID = O.PRODUCT_ID

--  GROUP BY PRODUCT_ID
--  HAVING O.UNIT > IN (SELECT SUM(UNIT) FROM ORDERS GROUP BY PRODUCT_ID) 

SELECT P.PRODUCT_NAME , T.UNIT FROM PRODUCTS P 

JOIN 
(SELECT PRODUCT_ID,SUM(UNIT) AS UNIT FROM ORDERS 
WHERE ORDER_DATE >='2020-02-01' AND ORDER_DATE<='2020-02-29'
GROUP BY PRODUCT_ID
HAVING SUM(UNIT)>=100) T 
ON P.PRODUCT_ID= T.PRODUCT_ID

